//! App template embedding and extraction
//!
//! Embeds the base Next.js app template for distribution.

use anyhow::{Context, Result};
use include_dir::{include_dir, Dir};
use std::fs;
use std::path::Path;
use tracing::debug;

/// Embedded app template from packages/app
/// Excludes: node_modules, .next, out, .git
static APP_TEMPLATE: Dir = include_dir!("$CARGO_MANIFEST_DIR/../../packages/app");

pub struct AppTemplate;

impl AppTemplate {
    /// Extract the embedded template to the target directory
    pub fn extract_to(target_dir: &Path) -> Result<()> {
        Self::extract_dir(&APP_TEMPLATE, target_dir)?;

        // Write .gitignore for generated directory
        let gitignore_content = r#"# Generated by yeollin prebuild
node_modules/
.next/
out/
"#;
        fs::write(target_dir.join(".gitignore"), gitignore_content)?;

        Ok(())
    }

    /// Recursively extract a directory
    fn extract_dir(dir: &Dir, target: &Path) -> Result<()> {
        fs::create_dir_all(target)
            .with_context(|| format!("Failed to create directory: {}", target.display()))?;

        // Extract files
        for file in dir.files() {
            let file_path = target.join(file.path().file_name().unwrap_or_default());

            // Skip files we don't want to extract
            let filename = file
                .path()
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("");

            if Self::should_skip_file(filename) {
                continue;
            }

            debug!("Extracting file: {}", file_path.display());
            fs::write(&file_path, file.contents())
                .with_context(|| format!("Failed to write file: {}", file_path.display()))?;
        }

        // Extract subdirectories
        for subdir in dir.dirs() {
            let dir_name = subdir
                .path()
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("");

            // Skip directories we don't want
            if Self::should_skip_dir(dir_name) {
                continue;
            }

            let subdir_path = target.join(dir_name);
            Self::extract_dir(subdir, &subdir_path)?;
        }

        Ok(())
    }

    /// Check if a file should be skipped during extraction
    fn should_skip_file(filename: &str) -> bool {
        matches!(
            filename,
            ".DS_Store"
                | "Thumbs.db"
                | ".gitkeep"
                | "bun.lockb"
                | "package-lock.json"
                | "yarn.lock"
                | "pnpm-lock.yaml"
        )
    }

    /// Check if a directory should be skipped during extraction
    fn should_skip_dir(dirname: &str) -> bool {
        matches!(
            dirname,
            "node_modules" | ".next" | "out" | ".git" | ".turbo" | "df" // devup-ui generated
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_template_has_required_files() {
        // Check that essential files are present in the embedded template
        assert!(
            APP_TEMPLATE.get_file("package.json").is_some(),
            "package.json should exist"
        );
        assert!(
            APP_TEMPLATE.get_file("next.config.ts").is_some(),
            "next.config.ts should exist"
        );
        assert!(
            APP_TEMPLATE.get_file("tsconfig.json").is_some(),
            "tsconfig.json should exist"
        );

        // Check src directory
        let src_dir = APP_TEMPLATE.get_dir("src");
        assert!(src_dir.is_some(), "src/ directory should exist");
    }
}
