//! App template embedding and extraction
//!
//! Embeds the base Next.js app template for distribution.

use anyhow::{Context, Result};
use futures_util::stream::{FuturesUnordered, StreamExt};
use include_dir::{include_dir, Dir, File};
use std::path::Path;
use tokio::fs;
use tracing::debug;

/// Embedded app template from packages/app
/// Excludes: node_modules, .next, out, .git
static APP_TEMPLATE: Dir = include_dir!("$CARGO_MANIFEST_DIR/../../packages/app");

pub struct AppTemplate;

impl AppTemplate {
    /// Extract the embedded template to the target directory
    pub async fn extract_to(target_dir: &Path) -> Result<()> {
        Self::extract_dir(&APP_TEMPLATE, target_dir).await?;

        // Write .gitignore for generated directory
        let gitignore_content = r#"# Generated by yeollin prebuild
node_modules/
.next/
out/
"#;
        fs::write(target_dir.join(".gitignore"), gitignore_content).await?;

        Ok(())
    }

    /// Recursively extract a directory with parallel file writes
    async fn extract_dir(dir: &Dir<'_>, target: &Path) -> Result<()> {
        fs::create_dir_all(target)
            .await
            .with_context(|| format!("Failed to create directory: {}", target.display()))?;

        // Collect files to extract (filter out skipped ones)
        let files_to_extract: Vec<(&File, std::path::PathBuf)> = dir
            .files()
            .filter_map(|file| {
                let filename = file
                    .path()
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("");

                if Self::should_skip_file(filename) {
                    None
                } else {
                    let file_path = target.join(file.path().file_name().unwrap_or_default());
                    Some((file, file_path))
                }
            })
            .collect();

        // Extract files IN PARALLEL
        let mut file_futures = FuturesUnordered::new();
        for (file, file_path) in files_to_extract {
            let contents = file.contents();
            file_futures.push(async move {
                debug!("Extracting file: {}", file_path.display());
                fs::write(&file_path, contents)
                    .await
                    .with_context(|| format!("Failed to write file: {}", file_path.display()))
            });
        }

        while let Some(result) = file_futures.next().await {
            result?;
        }

        // Collect subdirectories to extract
        let subdirs_to_extract: Vec<(&Dir, std::path::PathBuf)> = dir
            .dirs()
            .filter_map(|subdir| {
                let dir_name = subdir
                    .path()
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("");

                if Self::should_skip_dir(dir_name) {
                    None
                } else {
                    let subdir_path = target.join(dir_name);
                    Some((subdir, subdir_path))
                }
            })
            .collect();

        // Extract subdirectories IN PARALLEL
        let mut dir_futures = FuturesUnordered::new();
        for (subdir, subdir_path) in subdirs_to_extract {
            dir_futures.push(Self::extract_dir_owned(subdir, subdir_path));
        }

        while let Some(result) = dir_futures.next().await {
            result?;
        }

        Ok(())
    }

    /// Wrapper that takes ownership of the path for use with FuturesUnordered
    async fn extract_dir_owned(dir: &Dir<'_>, target: std::path::PathBuf) -> Result<()> {
        Self::extract_dir(dir, &target).await
    }

    /// Check if a file should be skipped during extraction
    fn should_skip_file(filename: &str) -> bool {
        matches!(
            filename,
            ".DS_Store"
                | "Thumbs.db"
                | ".gitkeep"
                | "bun.lockb"
                | "package-lock.json"
                | "yarn.lock"
                | "pnpm-lock.yaml"
        )
    }

    /// Check if a directory should be skipped during extraction
    fn should_skip_dir(dirname: &str) -> bool {
        matches!(
            dirname,
            "node_modules" | ".next" | "out" | ".git" | ".turbo" | "df" // devup-ui generated
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_template_has_required_files() {
        // Check that essential files are present in the embedded template
        assert!(
            APP_TEMPLATE.get_file("package.json").is_some(),
            "package.json should exist"
        );
        assert!(
            APP_TEMPLATE.get_file("next.config.ts").is_some(),
            "next.config.ts should exist"
        );
        assert!(
            APP_TEMPLATE.get_file("tsconfig.json").is_some(),
            "tsconfig.json should exist"
        );

        // Check src directory
        let src_dir = APP_TEMPLATE.get_dir("src");
        assert!(src_dir.is_some(), "src/ directory should exist");
    }
}
